### ISSUE TITLE
Flashupdate Driver not found.

### ISSUE THREAD

**Issue by DerElektrika** [GameboxSystems/Firmware-Update-Install-Scripts#3]
Hi there, i wanted to update the FW on my 64HD.
My kit is on version 1.6.4 and i have massive sound issues.
Had done all steps from your instructions. 

But when i want to update i got the message xusb22.sys not found .. its strange.. 
Can somebody please help me?
I have the Xilinx from Aliexpress. 
[_impactbatch.log](https://github.com/GameboxSystems/Firmware-Update-Install-Scripts/files/12059134/_impactbatch.log)

**Comment by GameboxSystems** [comment]
You may need to use the diligent driver. Install this driver, restart your system, and try again.

https://drive.google.com/file/d/1k-zYQ-TQy_3-2v6kryHmiKP5no4sHMkU/view?usp=sharing

**Comment by GameboxSystems** [comment]
@DerElektrika did this resolve your issue?

**Comment by GameboxSystems** [comment]
Marking as closed for now unless reported otherwise.
